### ISSUE TITLE
Answering your question...

### ISSUE THREAD

**Issue by Defman21** [cgchoffman/Assi-9#1]
Default console is a good tool if you know how to use it. In most cases you should define something like `var debug = true` or `var debug = false` and just check the variable when you want to log something in the console.
I can recommend you to try this: https://github.com/jonnyreeves/js-logger. It's similar to Komodo logger module because you can set your own levels, create custom handlers, etc.
Btw I also recommend to write your code in CoffeeScript instead of native JavaScript. When I moved to CoffeeScript I incensed my productivity because CoffeeScript looks more "humanly" and it gives you a lot of very useful shortcuts, functions, etc.
Just compare these two files: https://github.com/DevBevariour/ksfedit.or/blob/master/js/main.coffee and https://github.com/DevBevariour/ksfedit.or/blob/master/js/_/main.js. The first one is more smaller than the second one. Also the first one looks more readable IMO.

**Comment by cgchoffman** [comment]
Thanks Defman.  Probably could just email me or something for this rather than opening an issue.  I'm only worried about JS right now.  I'm familiar with but not interested in CoffeeScript for the moment.

"Incensed" isn't the word you're looking for by the way.  "increased" is what you meant.

**Comment by cgchoffman** [comment]
Note, these are just assignments for a course I'm taking.  They have to be implemented in a specific way and I only do the work to the point where I'll get the marks ;)  If there are bugs then i just don't have time to and don't have to fix them.  The question in the README.md is meant for my teach when he marks the assignment.

**Comment by Defman21** [comment]
Yeah of course I meant "increased"
